# Generated by Django 5.1.5 on 2025-01-31 23:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='expire_classes',
        ),
        migrations.RemoveField(
            model_name='client',
            name='expire_free_climbing',
        ),
        migrations.AddField(
            model_name='paymentticket',
            name='expire_time',
            field=models.DateField(blank=True, default=api.models.get_default_date_30_days, editable=False, null=True),
        ),
    ]
