# Generated by Django 5.1.5 on 2025-02-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_client_expire_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentticket',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentticket',
            name='type_of_service',
            field=models.CharField(choices=[('classes', 'CLASS'), ('free_climbing', 'FREE_CLIMBING')], max_length=30),
        ),
    ]
