# Generated by Django 5.1.5 on 2025-02-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paymentticket_is_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentticket',
            name='type_of_service',
            field=models.CharField(choices=[('classes', 'CLASSES'), ('free_climbing', 'FREE_CLIMBING')], max_length=30),
        ),
    ]
