# Generated by Django 5.1.5 on 2025-02-01 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_paymentticket_type_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
