# Generated by Django 5.1.5 on 2025-02-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_paymentticket_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentticket',
            name='amount_of_uses_LEFT',
            field=models.IntegerField(default=0),
        ),
    ]
