# Generated by Django 5.1.5 on 2025-02-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_client_classes_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentticket',
            name='type_of_service',
            field=models.CharField(choices=[('classes', 'classes'), ('free_climbing', 'free_climbing')], max_length=30),
        ),
    ]
