# Generated by Django 5.1.5 on 2025-02-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_paymentticket_type_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
