# Generated by Django 5.1.5 on 2025-02-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_client_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentticket',
            name='left_to_pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentticket',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentticket',
            name='status',
            field=models.CharField(choices=[('expired', 'expired'), ('in_use', 'in_use'), ('unpaid', 'unpaid')], default='expired', max_length=30),
        ),
    ]
