# Generated by Django 5.1.5 on 2025-02-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_paymentticket_left_to_pay_paymentticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentticket',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentticket',
            name='status',
            field=models.CharField(choices=[('expired', 'expired'), ('in_use', 'in_use'), ('unpaid', 'unpaid')], default='unpaid', max_length=30),
        ),
    ]
