# Generated by Django 5.1.6 on 2025-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_paymentticket_order_id_alter_paymentticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentticket',
            name='order_id',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
