# Generated by Django 5.1.6 on 2025-02-20 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_paymentticket_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_of_activity', models.CharField(choices=[('classes', 'classes'), ('free_climbing', 'free_climbing')], max_length=30)),
                ('hour', models.CharField(blank=True, choices=[('6-8', '6-8'), ('8-10', '8-10')], max_length=30, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paymentticket')),
            ],
            options={
                'unique_together': {('client', 'date')},
            },
        ),
    ]
