# Generated by Django 5.1.6 on 2025-02-21 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='type_of_activity',
            new_name='type_of_service',
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
