# Generated by Django 5.1.6 on 2025-02-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_type_of_activity_booking_type_of_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hour',
            field=models.CharField(blank=True, choices=[('6 to 8', '6 to 8'), ('8 to 10', '8 to 10')], max_length=30, null=True),
        ),
    ]
