# Generated by Django 5.1.5 on 2025-02-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_booking_type_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='type_of_service',
            field=models.CharField(blank=True, choices=[('classes', 'classes'), ('free_climbing', 'free_climbing')], max_length=30, null=True),
        ),
    ]
