# Generated by Django 5.1.6 on 2025-02-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_booking_hour_alter_booking_type_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentticket',
            name='payment_day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
