# Generated by Django 5.1.5 on 2025-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_paymentticket_payment_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPPassPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type_of_service', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('pass_amount', 'type_of_service')},
            },
        ),
    ]
