# Generated by Django 5.1.5 on 2025-02-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_mppassprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mppassprice',
            name='type_of_service',
            field=models.CharField(choices=[('classes', 'classes'), ('free_climbing', 'free_climbing')], max_length=30),
        ),
    ]
