# Generated by Django 5.1.5 on 2025-02-28 16:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_mppassprice_type_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentticket',
            name='expire_time',
            field=models.DateField(default=api.models.get_default_date_30_days),
        ),
    ]
